name: vorem
description: a peer to peer digital asset platform

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4
  country_code_picker: ^2.0.2
#  line_awesome_flutter: ^2.0.0
  sms_autofill:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
   - family: OpenSans_Bold
     fonts:
       - asset: fonts/OpenSans-Bold.ttf

   - family: OpenSans
     fonts:
       - asset: fonts/OpenSans-Regular.ttf



